import './geometry/binary-geometry.test';
import './sa/local-moran.test';
import './weights/contiguity-neighbors.test';
import './weights/nearest-neighbors.test';
import './mapping/quantile.test';
import './mapping/natural-breaks.test';
import './mapping/equal-interval-breaks.test';
import './mapping/percentile-breaks.test';
import './regression/linear-regression.test';
